# Site settings
title: ProjectArea:NOMIK
description: Minimal Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://nomikab.github.io/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nomik
user_description: Personal Website
user_title: 3D Printer Operator
user_title1: Web Developer
user_title2: Programmer
email: #
twitter_username: #
github_username:  nomikab
gplus_username:  #

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
